export const black = '#000000';
export const darkestGray = '#29292c';
export const darkGray = '#333';
export const darkPurple = '#282b36';
export const mediumGray = '#9b9aa1';
export const lightGray = '#d6d6d6';
export const lightWarmGray = '#f5f5f5';
export const offWhite = '#b7bdc5';
export const green = '#63d481';
export const tan = '#fcf8f2';
export const lightRed = 'rgba(244, 53, 30, 0.5)';
export const thoughtbotRed = '#ed3e44';
export const transparent = 'rgba(0, 0, 0, 0)';
export const white = '#ffffff';

export const main = '#f4351e';
export const mainDisabled = 'rgba(244, 53, 30, 0.5)';
export const secondary = '#f4351e';
export const header = '#030303';
export const screenBackground = '#263d5e';

export const baseText = white;
export const darkText = darkestGray;
export const loginText = white;
export const sectionBackground = lightWarmGray;
export const background = white;
export const enabled = main;
export const disabled = lightGray;
export const headerInactiveIcon = black;
